(minor) don't ignore dirty-ness when generating version number

diff --git a/src/gl-system-install b/src/gl-system-install
--- a/src/gl-system-install
+++ b/src/gl-system-install
@@ -70,7 +70,7 @@ perl -lpi -e "s(^GL_PACKAGE_CONF=.*)(GL_PACKAGE_CONF=$gl_conf_dir)" $buildroot$g
 # record which version is being sent across; we assume it's HEAD
 if git rev-parse --is-inside-work-tree >/dev/null 2>&1
 then
-    git describe --tags --long HEAD 2>/dev/null > conf/VERSION || die "git describe failed -- this should not happen!"
+    git describe --tags --long --dirty=-dt 2>/dev/null > conf/VERSION || die "git describe failed -- this should not happen!"
 else
     [ -f conf/VERSION ] || echo '(unknown)' > conf/VERSION
 fi
